### ISSUE TITLE
Unable to retrieve a non-json value from Secrets Manager

### ISSUE THREAD

**Issue by tlsimmons88** [t-botz/aws-secrets-manager-read-action#170]
Currently the action does not seem to support the ability to get any value from AWS Secrets manager that is not JSON.  Use case example:  flat text file like a license key.

Error:  SyntaxError: Unexpected token s in JSON at position 0

Steps:
1.  Go into AWS Secrets Manger
2.  Create a new secret of type other
3. Instead of giving it a key and value, click on the plain text fab and remove the JSON string
4. Type any plain text string you want
5. Give the secret and id and save it.
6. Try and get the value of the new secret using the GitHub Action.

If I make a direct AWS CLI call to the new id it is able to give me a valid response back.
Example CLI call:  aws secretsmanager get-secret-value --region us-west-2 --secret-id devGitHubActionPoCPlainText

I would expect this GitHub Action to return the value found in the SecretString field from AWS.

Thank you.

**Comment by t-botz** [comment]
It's supposed to handle as long as you don't use functionality that requires json.
Can you copy past how you use the action?

**Comment by tlsimmons88** [comment]
Hello, here is the step that I am trying to test this with
`- name: Get PLAINTEXT AWS Secret using t-botz's action
        id: plaintextsecrets
        uses: t-botz/aws-secrets-manager-read-action@v2.1.0
        with:
          secret-id: devGitHubActionPoCPlainText
          mask-json-values: false
          keys-as-env-vars: true
          keys-as-outputs: true
      - name: Use PLAINTEXT Secret
        run: |
          # Will actually display '***' as secret will be masked in output
          echo "${{ fromJSON(steps.plaintextsecrets.outputs.secret).devGitHubActionPoCPlainText }}"

          # Same result thanks to `keys-as-outputs: true`
          echo "${{ steps.plaintextsecrets.outputs.devGitHubActionPoCPlainText }}"

          # Same result thanks to `keys-as-env-vars: true`
          if [ -z ${devGitHubActionPoCPlainText+x} ]; then echo "devGitHubActionPoCPlainText is unset"; else echo "devGitHubActionPoCPlainText is set to '$devGitHubActionPoCPlainText'"; fi`

**Comment by t-botz** [comment]
@tlsimmons88 You are explicitely enabling json parsing by doing:

```
keys-as-env-vars: true
keys-as-outputs: true
```

I think what you are looking for is :

```yaml
  - name: Get PLAINTEXT AWS Secret using t-botz's action
    id: plaintextsecrets
    uses: t-botz/aws-secrets-manager-read-action@v2.1.0
    with:
      secret-id: devGitHubActionPoCPlainText
  - name: Use PLAINTEXT Secret
    run: |
      # Will actually display '***' as secret will be masked in output
      echo "${{steps.plaintextsecrets.outputs.secret}"   
```

 I should probably update the doc and the tests to illustrate that.
