### ISSUE TITLE
Integrate Multiple Secret IDs

### ISSUE THREAD

**Issue by daba-sharhan** [t-botz/aws-secrets-manager-read-action#53]
Is it possible to use multiple secret IDs in the `secret id` input section so that I can pull `key/values` from multiple secrets

**Comment by t-botz** [comment]
Nope but that should be fairly easy to implement.
If all secrets are json, merge the objects, otherwise throw an error

**Comment by daba-sharhan** [comment]
> @t-botz That will be a cool thing to implement, right

**Comment by t-botz** [comment]
I give it a thought and I think it's actually not worth. Combining two secrets make sense when they are key/values but given this action also outputs the raw secret, it then makes no sense to combine 2 strings. It's also ambiguous if two secrets have the same key.

The obvious workaround is to use the action twice.
```
- uses: t-botz/aws-secrets-manager-read-action@v2
  with:
    secret-id: foo1
    keys-as-env-vars: true
- uses: t-botz/aws-secrets-manager-read-action@v2
  with:
    secret-id: foo2
    keys-as-env-vars: true
```

The above is acceptable IMO because it removes the ambiguity and edge cases.
Also, given AWS Secrets pricing is per secret and fairly expensive, the pattern is usually to put all the secrets in the same place.

**Comment by kaykhan** [comment]
@t-botz 

I was also curious about this. We have seperated our keys like the following `prod/<service>` and we have maybe 5 or 6 of these which are json secrets. It costs us £0.40 per month for 5 or 6 keys not so expensive. Seperating them like this just makes it easier to know whats what especailly when you ahve a lot of secrets.

Would something like this be doable?

```
- uses: t-botz/aws-secrets-manager-read-action@v2
  with:
    secret-ids: [foo1, foo2]
    keys-as-env-vars: true
```

Then you prefix the secrets with the secret-id

```
echo "$FOO1_MY_SECRET"
echo "$FOO2_MY_SECRET"
```
